[pytest]
testpaths = tests
markers =
    branding: tests for EEA branding and logos
    user_menu: tests for EEA user menu customizations
    admin: tests for EEA admin area
    accessibility: tests for custom page accessibility
addopts = -vv -s --tb=short --strict-markers
